# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "restfulie-client"
  s.version = "1.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Guilherme Silveira, Caue Guerra, Luis Cipriani, Everton Ribeiro, George Guimaraes, Paulo Ahagon, and many more!"]
  s.date = "2012-05-06"
  s.description = "restfulie-client"
  s.email = "guilherme.silveira@caelum.com.br"
  s.extra_rdoc_files = [
    "LICENSE"
  ]
  s.files = [
    ".rspec",
    "Gemfile",
    "LICENSE",
    "Rakefile",
    "init.rb",
    "lib/restfulie-client.rb",
    "lib/restfulie-client/README.textile",
    "lib/restfulie-client/base.rb",
    "lib/restfulie-client/cache.rb",
    "lib/restfulie-client/cache/basic.rb",
    "lib/restfulie-client/cache/fake.rb",
    "lib/restfulie-client/cache/http_ext.rb",
    "lib/restfulie-client/cache/restrictions.rb",
    "lib/restfulie-client/common.rb",
    "lib/restfulie-client/common/error.rb",
    "lib/restfulie-client/common/logger.rb",
    "lib/restfulie-client/configuration.rb",
    "lib/restfulie-client/dsl.rb",
    "lib/restfulie-client/entry_point.rb",
    "lib/restfulie-client/ext.rb",
    "lib/restfulie-client/ext/http_ext.rb",
    "lib/restfulie-client/ext/link_ext.rb",
    "lib/restfulie-client/ext/open_search_ext.rb",
    "lib/restfulie-client/feature.rb",
    "lib/restfulie-client/feature/base.rb",
    "lib/restfulie-client/feature/base_request.rb",
    "lib/restfulie-client/feature/cache.rb",
    "lib/restfulie-client/feature/conneg_when_unaccepted.rb",
    "lib/restfulie-client/feature/enhance_response.rb",
    "lib/restfulie-client/feature/fake_response.rb",
    "lib/restfulie-client/feature/follow_request.rb",
    "lib/restfulie-client/feature/history.rb",
    "lib/restfulie-client/feature/history_request.rb",
    "lib/restfulie-client/feature/open_search.rb",
    "lib/restfulie-client/feature/open_search/pattern_matcher.rb",
    "lib/restfulie-client/feature/rescue_exception.rb",
    "lib/restfulie-client/feature/retry_when_unavailable.rb",
    "lib/restfulie-client/feature/serialize_body.rb",
    "lib/restfulie-client/feature/setup_header.rb",
    "lib/restfulie-client/feature/ssl_verify_mode_request.rb",
    "lib/restfulie-client/feature/throw_error_request.rb",
    "lib/restfulie-client/feature/verb.rb",
    "lib/restfulie-client/feature/with_timeout_request.rb",
    "lib/restfulie-client/http.rb",
    "lib/restfulie-client/http/cache.rb",
    "lib/restfulie-client/http/error.rb",
    "lib/restfulie-client/http/link_header.rb",
    "lib/restfulie-client/http/response_holder.rb",
    "lib/restfulie-client/master_delegator.rb",
    "lib/restfulie-client/mikyung.rb",
    "lib/restfulie-client/mikyung/concatenator.rb",
    "lib/restfulie-client/mikyung/core.rb",
    "lib/restfulie-client/mikyung/languages.rb",
    "lib/restfulie-client/mikyung/languages/german.rb",
    "lib/restfulie-client/mikyung/languages/portuguese.rb",
    "lib/restfulie-client/mikyung/rest_process_model.rb",
    "lib/restfulie-client/mikyung/steady_state_walker.rb",
    "lib/restfulie-client/mikyung/then_condition.rb",
    "lib/restfulie-client/mikyung/when_condition.rb",
    "lib/restfulie-client/stack_navigator.rb",
    "lib/restfulie-client/version.rb",
    "restfulie-client.gemspec"
  ]
  s.homepage = "http://restfulie.caelumobjects.com"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Hypermedia aware resource based library in ruby."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<medie>, ["~> 1.0.0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rspec-rails>, [">= 0"])
      s.add_development_dependency(%q<webmock>, [">= 0"])
    else
      s.add_dependency(%q<medie>, ["~> 1.0.0"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rspec-rails>, [">= 0"])
      s.add_dependency(%q<webmock>, [">= 0"])
    end
  else
    s.add_dependency(%q<medie>, ["~> 1.0.0"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rspec-rails>, [">= 0"])
    s.add_dependency(%q<webmock>, [">= 0"])
  end
end

